// Mocks generated by Mockito 5.4.6 from annotations
// in gym_app_alpha/test/src/services/payment_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter/foundation.dart' as _i2;
import 'package:flutter_stripe/src/stripe.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:stripe_platform_interface/stripe_platform_interface.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeValueListenable_0<T> extends _i1.SmartFake
    implements _i2.ValueListenable<T> {
  _FakeValueListenable_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlatformPayPaymentMethod_1 extends _i1.SmartFake
    implements _i3.PlatformPayPaymentMethod {
  _FakePlatformPayPaymentMethod_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSetupIntent_2 extends _i1.SmartFake implements _i3.SetupIntent {
  _FakeSetupIntent_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentIntent_3 extends _i1.SmartFake implements _i3.PaymentIntent {
  _FakePaymentIntent_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTokenData_4 extends _i1.SmartFake implements _i3.TokenData {
  _FakeTokenData_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentMethod_5 extends _i1.SmartFake implements _i3.PaymentMethod {
  _FakePaymentMethod_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAddToWalletResult_6 extends _i1.SmartFake
    implements _i3.AddToWalletResult {
  _FakeAddToWalletResult_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCanAddCardToWalletResult_7 extends _i1.SmartFake
    implements _i3.CanAddCardToWalletResult {
  _FakeCanAddCardToWalletResult_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIsCardInWalletResult_8 extends _i1.SmartFake
    implements _i3.IsCardInWalletResult {
  _FakeIsCardInWalletResult_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFinancialConnectionTokenResult_9 extends _i1.SmartFake
    implements _i3.FinancialConnectionTokenResult {
  _FakeFinancialConnectionTokenResult_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFinancialConnectionSessionResult_10 extends _i1.SmartFake
    implements _i3.FinancialConnectionSessionResult {
  _FakeFinancialConnectionSessionResult_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Stripe].
///
/// See the documentation for Mockito's code generation for more information.
class MockStripe extends _i1.Mock implements _i4.Stripe {
  MockStripe() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ValueListenable<bool> get isPlatformPaySupportedListenable =>
      (super.noSuchMethod(
        Invocation.getter(#isPlatformPaySupportedListenable),
        returnValue: _FakeValueListenable_0<bool>(
          this,
          Invocation.getter(#isPlatformPaySupportedListenable),
        ),
      ) as _i2.ValueListenable<bool>);

  @override
  bool get debugUpdatePlatformSheetCalled => (super.noSuchMethod(
        Invocation.getter(#debugUpdatePlatformSheetCalled),
        returnValue: false,
      ) as bool);

  @override
  bool get debugConfigurePlatformOrderTrackingCalled => (super.noSuchMethod(
        Invocation.getter(#debugConfigurePlatformOrderTrackingCalled),
        returnValue: false,
      ) as bool);

  @override
  set debugUpdatePlatformSheetCalled(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #debugUpdatePlatformSheetCalled,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set debugConfigurePlatformOrderTrackingCalled(bool? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #debugConfigurePlatformOrderTrackingCalled,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> applySettings() => (super.noSuchMethod(
        Invocation.method(
          #applySettings,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isPlatformPaySupported({
    _i3.IsGooglePaySupportedParams? googlePay,
    _i3.PlatformPayWebPaymentRequestCreateOptions?
        webPaymentRequestCreateOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isPlatformPaySupported,
          [],
          {
            #googlePay: googlePay,
            #webPaymentRequestCreateOptions: webPaymentRequestCreateOptions,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i3.PlatformPayPaymentMethod> createPlatformPayPaymentMethod({
    required _i3.PlatformPayPaymentMethodParams? params,
    bool? usesDeprecatedTokenFlow = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPlatformPayPaymentMethod,
          [],
          {
            #params: params,
            #usesDeprecatedTokenFlow: usesDeprecatedTokenFlow,
          },
        ),
        returnValue: _i5.Future<_i3.PlatformPayPaymentMethod>.value(
            _FakePlatformPayPaymentMethod_1(
          this,
          Invocation.method(
            #createPlatformPayPaymentMethod,
            [],
            {
              #params: params,
              #usesDeprecatedTokenFlow: usesDeprecatedTokenFlow,
            },
          ),
        )),
      ) as _i5.Future<_i3.PlatformPayPaymentMethod>);

  @override
  _i5.Future<_i3.SetupIntent> confirmPlatformPaySetupIntent({
    required String? clientSecret,
    required _i3.PlatformPayConfirmParams? confirmParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmPlatformPaySetupIntent,
          [],
          {
            #clientSecret: clientSecret,
            #confirmParams: confirmParams,
          },
        ),
        returnValue: _i5.Future<_i3.SetupIntent>.value(_FakeSetupIntent_2(
          this,
          Invocation.method(
            #confirmPlatformPaySetupIntent,
            [],
            {
              #clientSecret: clientSecret,
              #confirmParams: confirmParams,
            },
          ),
        )),
      ) as _i5.Future<_i3.SetupIntent>);

  @override
  _i5.Future<_i3.PaymentIntent> confirmPlatformPayPaymentIntent({
    required String? clientSecret,
    required _i3.PlatformPayConfirmParams? confirmParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmPlatformPayPaymentIntent,
          [],
          {
            #clientSecret: clientSecret,
            #confirmParams: confirmParams,
          },
        ),
        returnValue: _i5.Future<_i3.PaymentIntent>.value(_FakePaymentIntent_3(
          this,
          Invocation.method(
            #confirmPlatformPayPaymentIntent,
            [],
            {
              #clientSecret: clientSecret,
              #confirmParams: confirmParams,
            },
          ),
        )),
      ) as _i5.Future<_i3.PaymentIntent>);

  @override
  _i5.Future<void> updatePlatformSheet(
          {required _i3.PlatformPaySheetUpdateParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePlatformSheet,
          [],
          {#params: params},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> configurePlatformOrderTracking(
          {required _i3.PlatformPayOrderDetails? orderDetails}) =>
      (super.noSuchMethod(
        Invocation.method(
          #configurePlatformOrderTracking,
          [],
          {#orderDetails: orderDetails},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.TokenData> createApplePayToken(
          Map<String, dynamic>? payment) =>
      (super.noSuchMethod(
        Invocation.method(
          #createApplePayToken,
          [payment],
        ),
        returnValue: _i5.Future<_i3.TokenData>.value(_FakeTokenData_4(
          this,
          Invocation.method(
            #createApplePayToken,
            [payment],
          ),
        )),
      ) as _i5.Future<_i3.TokenData>);

  @override
  _i5.Future<_i3.PaymentMethod> createPaymentMethod({
    required _i3.PaymentMethodParams? params,
    _i3.PaymentMethodOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPaymentMethod,
          [],
          {
            #params: params,
            #options: options,
          },
        ),
        returnValue: _i5.Future<_i3.PaymentMethod>.value(_FakePaymentMethod_5(
          this,
          Invocation.method(
            #createPaymentMethod,
            [],
            {
              #params: params,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i3.PaymentMethod>);

  @override
  _i5.Future<_i3.TokenData> createToken(_i3.CreateTokenParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #createToken,
          [params],
        ),
        returnValue: _i5.Future<_i3.TokenData>.value(_FakeTokenData_4(
          this,
          Invocation.method(
            #createToken,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.TokenData>);

  @override
  _i5.Future<_i3.PaymentIntent> retrievePaymentIntent(String? clientSecret) =>
      (super.noSuchMethod(
        Invocation.method(
          #retrievePaymentIntent,
          [clientSecret],
        ),
        returnValue: _i5.Future<_i3.PaymentIntent>.value(_FakePaymentIntent_3(
          this,
          Invocation.method(
            #retrievePaymentIntent,
            [clientSecret],
          ),
        )),
      ) as _i5.Future<_i3.PaymentIntent>);

  @override
  _i5.Future<_i3.SetupIntent> retrieveSetupIntent(String? clientSecret) =>
      (super.noSuchMethod(
        Invocation.method(
          #retrieveSetupIntent,
          [clientSecret],
        ),
        returnValue: _i5.Future<_i3.SetupIntent>.value(_FakeSetupIntent_2(
          this,
          Invocation.method(
            #retrieveSetupIntent,
            [clientSecret],
          ),
        )),
      ) as _i5.Future<_i3.SetupIntent>);

  @override
  _i5.Future<void> openApplePaySetup() => (super.noSuchMethod(
        Invocation.method(
          #openApplePaySetup,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> handleURLCallback(String? url) => (super.noSuchMethod(
        Invocation.method(
          #handleURLCallback,
          [url],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i3.PaymentIntent> confirmPayment({
    required String? paymentIntentClientSecret,
    _i3.PaymentMethodParams? data,
    _i3.PaymentMethodOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmPayment,
          [],
          {
            #paymentIntentClientSecret: paymentIntentClientSecret,
            #data: data,
            #options: options,
          },
        ),
        returnValue: _i5.Future<_i3.PaymentIntent>.value(_FakePaymentIntent_3(
          this,
          Invocation.method(
            #confirmPayment,
            [],
            {
              #paymentIntentClientSecret: paymentIntentClientSecret,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i3.PaymentIntent>);

  @override
  _i5.Future<_i3.PaymentIntent> handleNextAction(
    String? paymentIntentClientSecret, {
    String? returnURL,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleNextAction,
          [paymentIntentClientSecret],
          {#returnURL: returnURL},
        ),
        returnValue: _i5.Future<_i3.PaymentIntent>.value(_FakePaymentIntent_3(
          this,
          Invocation.method(
            #handleNextAction,
            [paymentIntentClientSecret],
            {#returnURL: returnURL},
          ),
        )),
      ) as _i5.Future<_i3.PaymentIntent>);

  @override
  _i5.Future<_i3.SetupIntent> handleNextActionForSetupIntent(
    String? setupIntentClientSecret, {
    String? returnURL,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleNextActionForSetupIntent,
          [setupIntentClientSecret],
          {#returnURL: returnURL},
        ),
        returnValue: _i5.Future<_i3.SetupIntent>.value(_FakeSetupIntent_2(
          this,
          Invocation.method(
            #handleNextActionForSetupIntent,
            [setupIntentClientSecret],
            {#returnURL: returnURL},
          ),
        )),
      ) as _i5.Future<_i3.SetupIntent>);

  @override
  _i5.Future<_i3.SetupIntent> confirmSetupIntent({
    required String? paymentIntentClientSecret,
    required _i3.PaymentMethodParams? params,
    _i3.PaymentMethodOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmSetupIntent,
          [],
          {
            #paymentIntentClientSecret: paymentIntentClientSecret,
            #params: params,
            #options: options,
          },
        ),
        returnValue: _i5.Future<_i3.SetupIntent>.value(_FakeSetupIntent_2(
          this,
          Invocation.method(
            #confirmSetupIntent,
            [],
            {
              #paymentIntentClientSecret: paymentIntentClientSecret,
              #params: params,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i3.SetupIntent>);

  @override
  _i5.Future<String?> createTokenForCVCUpdate(String? cvc) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTokenForCVCUpdate,
          [cvc],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<_i3.PaymentSheetPaymentOption?> initPaymentSheet(
          {required _i3.SetupPaymentSheetParameters? paymentSheetParameters}) =>
      (super.noSuchMethod(
        Invocation.method(
          #initPaymentSheet,
          [],
          {#paymentSheetParameters: paymentSheetParameters},
        ),
        returnValue: _i5.Future<_i3.PaymentSheetPaymentOption?>.value(),
      ) as _i5.Future<_i3.PaymentSheetPaymentOption?>);

  @override
  _i5.Future<_i3.PaymentSheetPaymentOption?> presentPaymentSheet(
          {_i3.PaymentSheetPresentOptions? options}) =>
      (super.noSuchMethod(
        Invocation.method(
          #presentPaymentSheet,
          [],
          {#options: options},
        ),
        returnValue: _i5.Future<_i3.PaymentSheetPaymentOption?>.value(),
      ) as _i5.Future<_i3.PaymentSheetPaymentOption?>);

  @override
  _i5.Future<void> intentCreationCallback(
          _i3.IntentCreationCallbackParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #intentCreationCallback,
          [params],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resetPaymentSheetCustomer() => (super.noSuchMethod(
        Invocation.method(
          #resetPaymentSheetCustomer,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> confirmPaymentSheetPayment() => (super.noSuchMethod(
        Invocation.method(
          #confirmPaymentSheetPayment,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> dangerouslyUpdateCardDetails(_i3.CardDetails? card) =>
      (super.noSuchMethod(
        Invocation.method(
          #dangerouslyUpdateCardDetails,
          [card],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> initGooglePay(_i3.GooglePayInitParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #initGooglePay,
          [params],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> presentGooglePay(_i3.PresentGooglePayParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #presentGooglePay,
          [params],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.PaymentMethod> createGooglePayPaymentMethod(
          _i3.CreateGooglePayPaymentParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #createGooglePayPaymentMethod,
          [params],
        ),
        returnValue: _i5.Future<_i3.PaymentMethod>.value(_FakePaymentMethod_5(
          this,
          Invocation.method(
            #createGooglePayPaymentMethod,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.PaymentMethod>);

  @override
  _i5.Future<bool> isGooglePaySupported(
          _i3.IsGooglePaySupportedParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #isGooglePaySupported,
          [params],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i3.PaymentIntent> collectBankAccount({
    required bool? isPaymentIntent,
    required String? clientSecret,
    required _i3.CollectBankAccountParams? params,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #collectBankAccount,
          [],
          {
            #isPaymentIntent: isPaymentIntent,
            #clientSecret: clientSecret,
            #params: params,
          },
        ),
        returnValue: _i5.Future<_i3.PaymentIntent>.value(_FakePaymentIntent_3(
          this,
          Invocation.method(
            #collectBankAccount,
            [],
            {
              #isPaymentIntent: isPaymentIntent,
              #clientSecret: clientSecret,
              #params: params,
            },
          ),
        )),
      ) as _i5.Future<_i3.PaymentIntent>);

  @override
  _i5.Future<_i3.PaymentIntent> verifyPaymentIntentWithMicrodeposits({
    required bool? isPaymentIntent,
    required String? clientSecret,
    required _i3.VerifyMicroDepositsParams? params,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyPaymentIntentWithMicrodeposits,
          [],
          {
            #isPaymentIntent: isPaymentIntent,
            #clientSecret: clientSecret,
            #params: params,
          },
        ),
        returnValue: _i5.Future<_i3.PaymentIntent>.value(_FakePaymentIntent_3(
          this,
          Invocation.method(
            #verifyPaymentIntentWithMicrodeposits,
            [],
            {
              #isPaymentIntent: isPaymentIntent,
              #clientSecret: clientSecret,
              #params: params,
            },
          ),
        )),
      ) as _i5.Future<_i3.PaymentIntent>);

  @override
  _i5.Future<_i3.AddToWalletResult> canAddToWallet(String? last4) =>
      (super.noSuchMethod(
        Invocation.method(
          #canAddToWallet,
          [last4],
        ),
        returnValue:
            _i5.Future<_i3.AddToWalletResult>.value(_FakeAddToWalletResult_6(
          this,
          Invocation.method(
            #canAddToWallet,
            [last4],
          ),
        )),
      ) as _i5.Future<_i3.AddToWalletResult>);

  @override
  _i5.Future<_i3.CanAddCardToWalletResult> canAddCardToWallet(
          _i3.CanAddCardToWalletParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #canAddCardToWallet,
          [params],
        ),
        returnValue: _i5.Future<_i3.CanAddCardToWalletResult>.value(
            _FakeCanAddCardToWalletResult_7(
          this,
          Invocation.method(
            #canAddCardToWallet,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.CanAddCardToWalletResult>);

  @override
  _i5.Future<_i3.IsCardInWalletResult> isCardInWallet(String? cardLastFour) =>
      (super.noSuchMethod(
        Invocation.method(
          #isCardInWallet,
          [cardLastFour],
        ),
        returnValue: _i5.Future<_i3.IsCardInWalletResult>.value(
            _FakeIsCardInWalletResult_8(
          this,
          Invocation.method(
            #isCardInWallet,
            [cardLastFour],
          ),
        )),
      ) as _i5.Future<_i3.IsCardInWalletResult>);

  @override
  _i5.Future<_i3.FinancialConnectionTokenResult> collectBankAccountToken(
          {required String? clientSecret}) =>
      (super.noSuchMethod(
        Invocation.method(
          #collectBankAccountToken,
          [],
          {#clientSecret: clientSecret},
        ),
        returnValue: _i5.Future<_i3.FinancialConnectionTokenResult>.value(
            _FakeFinancialConnectionTokenResult_9(
          this,
          Invocation.method(
            #collectBankAccountToken,
            [],
            {#clientSecret: clientSecret},
          ),
        )),
      ) as _i5.Future<_i3.FinancialConnectionTokenResult>);

  @override
  _i5.Future<_i3.FinancialConnectionSessionResult>
      collectFinancialConnectionsAccounts({required String? clientSecret}) =>
          (super.noSuchMethod(
            Invocation.method(
              #collectFinancialConnectionsAccounts,
              [],
              {#clientSecret: clientSecret},
            ),
            returnValue: _i5.Future<_i3.FinancialConnectionSessionResult>.value(
                _FakeFinancialConnectionSessionResult_10(
              this,
              Invocation.method(
                #collectFinancialConnectionsAccounts,
                [],
                {#clientSecret: clientSecret},
              ),
            )),
          ) as _i5.Future<_i3.FinancialConnectionSessionResult>);

  @override
  _i5.Future<_i3.CustomerSheetResult?> initCustomerSheet(
          {required _i3.CustomerSheetInitParams? customerSheetInitParams}) =>
      (super.noSuchMethod(
        Invocation.method(
          #initCustomerSheet,
          [],
          {#customerSheetInitParams: customerSheetInitParams},
        ),
        returnValue: _i5.Future<_i3.CustomerSheetResult?>.value(),
      ) as _i5.Future<_i3.CustomerSheetResult?>);

  @override
  _i5.Future<_i3.CustomerSheetResult?> presentCustomerSheet(
          {_i3.CustomerSheetPresentParams? options}) =>
      (super.noSuchMethod(
        Invocation.method(
          #presentCustomerSheet,
          [],
          {#options: options},
        ),
        returnValue: _i5.Future<_i3.CustomerSheetResult?>.value(),
      ) as _i5.Future<_i3.CustomerSheetResult?>);

  @override
  _i5.Future<_i3.CustomerSheetResult?>
      retrieveCustomerSheetPaymentOptionSelection() => (super.noSuchMethod(
            Invocation.method(
              #retrieveCustomerSheetPaymentOptionSelection,
              [],
            ),
            returnValue: _i5.Future<_i3.CustomerSheetResult?>.value(),
          ) as _i5.Future<_i3.CustomerSheetResult?>);

  @override
  void markNeedsSettings() => super.noSuchMethod(
        Invocation.method(
          #markNeedsSettings,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
